"""empty message

Revision ID: 95edce4b575c
Revises: d9affd9eea91
Create Date: 2022-07-26 15:27:23.835914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95edce4b575c'
down_revision = 'd9affd9eea91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_images', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business_images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_images', type_='foreignkey')
    op.drop_column('business_images', 'user_id')
    # ### end Alembic commands ###
